
import 'package:flutter/material.dart';
import 'package:rotation_champs/models/champion_model.dart';
import 'package:rotation_champs/providers/champion_provider.dart';

 class HomePage extends StatelessWidget {
 final ChampionProvider championProvider=new ChampionProvider();
 
   @override
   Widget build(BuildContext context) {
     return Scaffold(
      appBar: AppBar(
        title:Text('Champions'),
        backgroundColor: Colors.blue[600]// Generated by https://quicktype.io
      ),
      body: _championList(context),
     );
   }
 Widget _championList(BuildContext context){
  return FutureBuilder(
    future: championProvider.getAll(),
    builder: (context,AsyncSnapshot snapshot){
      if(snapshot.hasData){
        return ListView.builder(
          padding: EdgeInsets.all(10.0),
          itemCount:snapshot.data.length,
          itemBuilder: (context, index) {
            final Champion champ= snapshot.data[index];
            return _championCard(context,champ);
          },

        );
      } 
      else {
          return Container(
            height: 400.0,
            child: Center(
              child:CircularProgressIndicator()
            ),
          );
        }
      
    },
  );
 }

  Widget _championCard(BuildContext context,Champion champ) {
    
    return Card(
      margin: EdgeInsets.only(left: 10.0, top: 10.0),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(20.0),
      ),
      child: _getInfoChamp(context,champ),
    ); 
  
  }  
  Widget _getInfoChamp(BuildContext context,Champion champ){
    return ListTile(
        onTap: (){
          Navigator.pushNamed(context,'detalle',arguments: champ.id);
        },
      leading:Hero(
        tag: champ.id,
        child: ClipRRect(
        borderRadius: BorderRadius.circular(30.0),
        child:FadeInImage(        
          height: 100.0,        
          image: AssetImage("assets/img/default/${champ.getDefaultImg()}") ,
          placeholder: AssetImage("assets/img/no-image.jpg"),
          )
        ),
      ) ,
      title: Text(champ.name),
      subtitle: Text(champ.title),
      );
    /*return List
          (
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          children: [
            SizedBox(width: 20.0,),
            Expanded(
              child:ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child:FadeInImage(
                  
                  image: AssetImage("assets/img/default/${champ.getDefaultImg()}") ,
                  placeholder: AssetImage("assets/img/loading.gif"),
                )
              )  
            ),
            SizedBox(width: 20.0,),
            //Image(image: AssetImage()),
            Text(champ.name),
            Spacer(),
            Expanded(
              child: Icon(Icons.arrow_forward_ios)
            ),
          ],
        );*/
  }
 }