// Generated by https://quicktype.io
class ChampionsDetailedInfo{
  List<ChampionDetailedInfo> items= new List();
  ChampionsDetailedInfo();
  ChampionsDetailedInfo.fromJsonMap(Map<String,dynamic> jsonMap){
    if(jsonMap==null) return;
    jsonMap.forEach((key, value) { 
      final champ=ChampionDetailedInfo.fromJsonMap(value);
      items.add(champ);
    });
  }
}

class ChampionDetailedInfo {
  String id;
  String key;
  String name;
  String title;
  List<Skin> skins=[];
  String lore;
  List<String> tags;
  Info info;
  Map<String, dynamic> stats;


  ChampionDetailedInfo({
    this.id,
    this.key,
    this.name,
    this.title,
    this.skins,
    this.lore,
    this.tags,
    this.info,
    this.stats,
    
  });
  ChampionDetailedInfo.fromJsonMap(Map<String,dynamic> json){
   
    this.id=json['id'];
    this.key=json['key'];
    this.name=json['name'];
    this.title=json['title'];
    for(var item in json['skins']){
      final skin= new Skin.fromJsonMap(item);
      this.skins.add(skin);
   }
    this.lore= json['lore'];
    this.tags=json['tags'].cast<String>();
    this.info= Info.fromJsonMap(json['info']);
    this.stats=json['stats'];
  }
  String getDefaultImg(){
   return "${this.id}_0.jpg";
  }  
}

class Info {
  int attack;
  int defense;
  int magic;
  int difficulty;

  Info({
    this.attack,
    this.defense,
    this.magic,
    this.difficulty,
  });
  Info.fromJsonMap(Map<String,dynamic> json){
    this.attack     = json['attack'];
    this.defense    = json['defense'];
    this.magic      = json['magic'];
    this.difficulty = json['difficulty'];
  }
}

class Skin {
  String id;
  int num;
  String name;
  bool chromas;

  Skin({
    this.id,
    this.num,
    this.name,
    this.chromas,
  });
  Skin.fromJsonMap(Map<String,dynamic> json){
    this.id     = json['id'];
    this.num    = json['num'];
    this.name   = json['name'];
    this.chromas=json['chromas'];
  }
  String getFoto(String id){
    return "${id}_${this.num}.jpg";
  }
}
